# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.CharField(max_length=100, verbose_name='电子邮箱')),
                ('tel', models.CharField(max_length=50, verbose_name='电话')),
                ('message', models.TextField(max_length=1000, verbose_name='留言')),
            ],
            options={
                'verbose_name_plural': '留言信息库',
                'ordering': ['id'],
                'verbose_name': '留言信息',
            },
        ),
    ]
