# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
    ]
