# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170612_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '新闻分类',
                'verbose_name': '新闻分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='姓名')),
                ('arthur', models.CharField(blank=True, max_length=500, null=True, verbose_name='作者')),
                ('img', models.FileField(upload_to='img/', verbose_name='主要图片（480*270）')),
                ('summary', models.CharField(blank=True, max_length=5000, null=True, verbose_name='文章简介')),
                ('content', models.TextField(blank=True, max_length=500000, null=True, verbose_name='文章内容')),
                ('dimdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='upload/', verbose_name='图片')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dimDate'],
                'verbose_name': '图片新闻',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '新闻标签',
                'verbose_name': '新闻标签',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
