# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170621_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-dimdate'], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterModelOptions(
            name='newsimg',
            options={'ordering': ['-dimDate'], 'verbose_name': '图片新闻', 'verbose_name_plural': '图片新闻'},
        ),
    ]
