# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170621_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.FileField(upload_to='/static/img/', verbose_name='主要图片（480*270）'),
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='Image',
            field=models.FileField(upload_to='/static/upload/', verbose_name='图片'),
        ),
    ]
