# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170622_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章详情')),
                ('viewedTimes', models.IntegerField(verbose_name='浏览次数')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='文章类型')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文章',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('link', models.CharField(blank=True, max_length=50, verbose_name='链接地址（可为空）')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='子标题')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '轮播管理',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('orderId', models.CharField(max_length=20, verbose_name='下一个流程id号')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '流程表',
                'verbose_name_plural': '流程们',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='flowgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '流程组表',
                'verbose_name_plural': '流程组们',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('caption', models.CharField(blank=True, max_length=34, null=True, verbose_name='内容')),
                ('filepath', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件地址')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片库',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, unique=True, verbose_name='登录名')),
                ('pwd', models.CharField(blank=True, max_length=34, null=True, verbose_name='密码')),
                ('salt', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码盐值')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户类型')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
                ('avt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture')),
            ],
            options={
                'verbose_name': '用户资料表',
                'verbose_name_plural': 'users',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='flowgroup',
            name='user',
            field=models.ManyToManyField(to='core.user'),
        ),
        migrations.AddField(
            model_name='flow',
            name='groupName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flowgroup'),
        ),
        migrations.AddField(
            model_name='flow',
            name='user',
            field=models.ManyToManyField(to='core.user'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='imgs',
            field=models.ManyToManyField(to='core.picture'),
        ),
        migrations.AddField(
            model_name='article',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture'),
        ),
    ]
